apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 15.0.7
    helm:
      values: |
        auth:
          existingSecret: minio-credentials
          rootUserSecretKey: rootUser
          rootPasswordSecretKey: rootPassword

        defaultBuckets: "mlflow-artifacts"

        service:
          type: ClusterIP
          ports:
            api: 9000
            console: 9001

        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
