apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: mlflow
spec:
  project: default

  source:
    repoURL: https://github.com/102012dl/mlops-hw9.git
    targetRevision: main
    path: experiments/mlflow

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
