apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.32
    helm:
      values: |
        auth:
          username: "mlflow"
          database: "mlflow"
          existingSecret: postgres-credentials
          secretKeys:
            userPasswordKey: password

        primary:
          persistence:
            enabled: false

        service:
          type: ClusterIP
          ports:
            postgresql: 5432
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
